batuhan
bounswe/2021SpringGroup12 pull request #136
Opened 2021-05-30 16:22 UTC by batuhanovski

Ingredients and Instruction Finder for Cocktails

To see the ingredients, glass type and instructions of cocktails which have keyword in its name: http://127.0.0.1:5000/cocktails/?cocktail_name=**keyword**

To post a cocktail use json in this format (example):
{
    "strDrink": "batuhancocktail",
    "strIngredient1": "gin",
    "strIngredient2": "tonic",
    "strIngredient3": "lemon",
    "strIngredient4": "blueberry",
    "strGlass": "a long glass",
    "strInstructions": "squeeze the lemon and mix all espri"
}

2021-05-30 16:51 UTC, veyisTurgut commented
Your name could stay in branch name so that we can find your work easily in the future.

2021-05-30 16:55 UTC, veyisTurgut requested changes
As you know we changed folder structure recently, please obey that structure. 
And don't forget to documentate your awesome endpoints

2021-06-01 17:53 UTC, gokayyildiz commented
Batu, you should update the relative path calls with respect to the new folder structure.
To achieve this you can firstly copy the folder structure on main branch into your branch and add your changes by looking at github. It may be not the best practice but we should do it

2021-06-04 18:26 UTC, gokayyildiz reviewed
seems good

2021-06-04 18:27 UTC, veyisTurgut commented
Could you please change `practice-app.py` to `main.py` and add `pycache` folder to `.gitignore` ?

2021-06-08 18:49 UTC, Refref18 requested changes

2021-06-08 18:49 UTC, Refref18 commented on practice-app/src/main/templates/create_cocktail.html
> +<html>
I hope you'll convert them into .vue so that it will be easier for creating frontend as a group

2021-06-08 18:49 UTC, Refref18 commented on practice-app/src/main/db/mapper.py
> +def currency_rate_mapper(currency_rate: dict) -> CurrencyRate:
why there exist 2 mapper for coctail?

2021-06-09 08:07 UTC, batuhanovski reviewed
# #

2021-06-09 08:11 UTC, closed without merging

2021-06-09 08:13 UTC, batuhanovski commented on practice-app/src/main/db/mapper.py
> +def currency_rate_mapper(currency_rate: dict) -> CurrencyRate:
There is one?

2021-06-13 10:30 UTC, Refref18 commented
As I said during the [meeting](https://github.com/bounswe/2021SpringGroup12/wiki/Meeting-%2314-(01.06.2021) I gave feedback to batuhan about changing his file structure,I would like to point out this note that we did not add to the conservation so that the progress can be examined more easily.